// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pbwnjoesbrjxkacxgwex.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBid25qb2VzYnJqeGthY3hnd2V4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4NDU2ODMsImV4cCI6MjA3NzQyMTY4M30.-jTkQibYEkgx1e0ik2edQrWkdbZF7jNSgX9WBdf9qTc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});